/**
 * growth/context/CreatorGrowthContext.jsx — Creator Growth Context
 *
 * Module 10.4 — Realis Creator Growth Engine
 *
 * Stores the latest CreatorGrowthPlan generated by creatorGrowthService.
 * It is a derived-state store: GrowthBridge writes to it; UI reads from it.
 *
 * ── State ─────────────────────────────────────────────────────────────────────
 *   growthPlan    — latest CreatorGrowthPlan (see growthModel.js)
 *   isGenerating  — true while GrowthBridge is computing a new plan
 *   refreshTick   — incremented by refreshGrowth() to signal the bridge
 *
 * ── Actions ───────────────────────────────────────────────────────────────────
 *   SET_PLAN           — replace growthPlan with a freshly-generated one
 *   SET_GENERATING     — toggle the loading indicator
 *   COMPLETE_MILESTONE — mark a single milestone completed by its id
 *   REFRESH_TICK       — increment so GrowthBridge regenerates on demand
 *
 * ── Public API ────────────────────────────────────────────────────────────────
 *   growthPlan              — CreatorGrowthPlan
 *   isGenerating            — boolean
 *   setGrowthPlan(plan)     — write a generated plan (called by GrowthBridge)
 *   setGenerating(v)        — set the loading indicator (called by GrowthBridge)
 *   completeMilestone(id)   — mark a milestone completed (called by UI)
 *   refreshGrowth()         — force GrowthBridge to regenerate (called by UI)
 *
 * ── Mounting ──────────────────────────────────────────────────────────────────
 * Wrapped inside CreatorCoachProvider in App.jsx — the new innermost provider:
 *   CreatorCoachProvider
 *     └─ CreatorGrowthProvider  ← here
 *        └─ BrowserRouter
 *           └─ GrowthBridge (renderless, writes growthPlan)
 */

import React, {
  createContext,
  useContext,
  useReducer,
  useCallback,
  useMemo,
} from 'react';

import { createBlankGrowthPlan } from '../models/growthModel';

// ── Action type constants ──────────────────────────────────────────────────────
const A = {
  SET_PLAN:           'SET_PLAN',
  SET_GENERATING:     'SET_GENERATING',
  COMPLETE_MILESTONE: 'COMPLETE_MILESTONE',
  REFRESH_TICK:       'REFRESH_TICK',
};

// ── Initial state ─────────────────────────────────────────────────────────────
const initialState = {
  growthPlan:   createBlankGrowthPlan(),
  isGenerating: false,
  refreshTick:  0,
};

// ── Reducer ───────────────────────────────────────────────────────────────────
function reducer(state, action) {
  switch (action.type) {

    case A.SET_PLAN:
      return { ...state, growthPlan: action.payload, isGenerating: false };

    case A.SET_GENERATING:
      return { ...state, isGenerating: action.payload };

    case A.COMPLETE_MILESTONE: {
      const updatedMilestones = state.growthPlan.milestones.map(m =>
        m.id === action.payload ? { ...m, completed: true, currentValue: m.targetValue } : m,
      );
      return {
        ...state,
        growthPlan: { ...state.growthPlan, milestones: updatedMilestones },
      };
    }

    case A.REFRESH_TICK:
      return { ...state, refreshTick: state.refreshTick + 1 };

    default:
      return state;
  }
}

// ── Context ───────────────────────────────────────────────────────────────────
const CreatorGrowthContext = createContext(null);

export function CreatorGrowthProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);

  // ── Action creators ──────────────────────────────────────────────────────

  /** Write a newly-generated CreatorGrowthPlan. Called by GrowthBridge. */
  const setGrowthPlan = useCallback(
    (plan) => dispatch({ type: A.SET_PLAN, payload: plan }),
    [],
  );

  /** Set the generating indicator. Called by GrowthBridge. */
  const setGenerating = useCallback(
    (value) => dispatch({ type: A.SET_GENERATING, payload: value }),
    [],
  );

  /**
   * Mark a milestone as completed.
   * Called by the growth UI when the creator taps a milestone row.
   * @param {string} milestoneId
   */
  const completeMilestone = useCallback(
    (milestoneId) => dispatch({ type: A.COMPLETE_MILESTONE, payload: milestoneId }),
    [],
  );

  /**
   * Increment the refresh tick to force GrowthBridge to regenerate even if
   * no upstream signal changed.
   */
  const refreshGrowth = useCallback(
    () => dispatch({ type: A.REFRESH_TICK }),
    [],
  );

  // ── Context value ────────────────────────────────────────────────────────

  const value = useMemo(() => ({
    // Raw state
    state,

    // Convenience top-level accessors
    growthPlan:   state.growthPlan,
    isGenerating: state.isGenerating,

    // Action creators
    setGrowthPlan,
    setGenerating,
    completeMilestone,
    refreshGrowth,
  }), [state, setGrowthPlan, setGenerating, completeMilestone, refreshGrowth]);

  return (
    <CreatorGrowthContext.Provider value={value}>
      {children}
    </CreatorGrowthContext.Provider>
  );
}

/**
 * Internal context hook — consumed by useCreatorGrowth.js and GrowthBridge.
 * Components should import useCreatorGrowth from the public hook, not this.
 */
export function useCreatorGrowthContext() {
  const ctx = useContext(CreatorGrowthContext);
  if (!ctx) {
    throw new Error('useCreatorGrowthContext must be used within CreatorGrowthProvider');
  }
  return ctx;
}
