/**
 * assistant/models/assistantModel.js — Creator Assistant Model
 *
 * Module 10.1 — Realis AI Creator Assistant
 *
 * Defines the canonical shape of a CreatorBriefing and provides
 * a factory function that returns a safe blank instance.
 *
 * A CreatorBriefing is a personalised daily briefing generated by
 * creatorAssistantService from three data sources:
 *   • CreatorLearningProfile  (from CreatorLearningContext)
 *   • AnalyticsStatistics     (from AnalyticsContext)
 *   • MemoryProfile + Stats   (from CreatorMemoryContext)
 *
 * ── Typedefs ───────────────────────────────────────────────────────────────────
 *
 * @typedef {object} BriefingCameraSettings
 * @property {string|null}  resolution
 * @property {number|null}  fps
 * @property {boolean|null} hdr
 * @property {string|null}  flash
 * @property {string|null}  stabilization
 * @property {string|null}  focusMode
 * @property {string|null}  whiteBalance
 *
 * @typedef {object} CreatorBriefing
 * @property {string}                  generatedAt        ISO timestamp
 * @property {string}                  greeting           Personalised greeting string
 * @property {string}                  aiRecommendation   Primary AI recommendation sentence
 * @property {string|null}             recommendedWorkflow  Workflow name to use today
 * @property {string|null}             recommendedWorkflowId
 * @property {BriefingCameraSettings|null} recommendedCameraSettings
 * @property {number}                  expectedQuality    0–100 predicted quality score
 * @property {number}                  confidence         0–100 confidence in this briefing
 * @property {string[]}                reasons            Array of reason strings (why this rec)
 * @property {string}                  dailyGoal          Short motivational creative goal
 * @property {string}                  ctaLabel           Call-to-action button label
 * @property {string}                  ctaPath            Route to navigate to on CTA press
 * @property {'high'|'medium'|'low'}   priority           Overall briefing priority tier
 */

// ── Factory ────────────────────────────────────────────────────────────────────

/**
 * Returns a blank CreatorBriefing with all fields set to their safe empty
 * defaults.  Used as the initial state of CreatorAssistantContext before
 * the first generation run.
 *
 * @returns {CreatorBriefing}
 */
export function createBlankBriefing() {
  return {
    generatedAt:               null,
    greeting:                  'Good day, Creator.',
    aiRecommendation:          'Start shooting to unlock your personalised AI briefing.',
    recommendedWorkflow:       null,
    recommendedWorkflowId:     null,
    recommendedCameraSettings: null,
    expectedQuality:           0,
    confidence:                0,
    reasons:                   [],
    dailyGoal:                 'Begin your creative session and let AI guide your next shot.',
    ctaLabel:                  'Open Camera',
    ctaPath:                   '/camera',
    priority:                  'low',
  };
}
