/**
 * coach/context/CreatorCoachContext.jsx — Creator Coach Context
 *
 * Module 10.3 — Realis Creator Coach Engine
 *
 * Stores the latest CreatorCoachSession generated by creatorCoachService.
 * It is a derived-state store: CoachBridge writes to it; UI reads from it.
 *
 * ── State ─────────────────────────────────────────────────────────────────────
 *   coachSession   — latest CreatorCoachSession (see coachModel.js)
 *   isGenerating   — true while CoachBridge is computing a new session
 *   refreshTick    — incremented by refreshCoach() to signal the bridge
 *
 * ── Actions ───────────────────────────────────────────────────────────────────
 *   SET_SESSION    — replace coachSession with a freshly-generated one
 *   SET_GENERATING — toggle the loading indicator
 *   COMPLETE_ACTION— mark a single CoachAction completed by its id
 *   REFRESH_TICK   — increment so CoachBridge regenerates on demand
 *
 * ── Public API ────────────────────────────────────────────────────────────────
 *   coachSession          — CreatorCoachSession
 *   isGenerating          — boolean
 *   setCoachSession(s)    — write a generated session (called by CoachBridge)
 *   setGenerating(v)      — set the loading indicator (called by CoachBridge)
 *   completeAction(id)    — mark a CoachAction completed (called by UI)
 *   refreshCoach()        — force CoachBridge to regenerate (called by UI)
 *
 * ── Mounting ──────────────────────────────────────────────────────────────────
 * Wrapped inside CreatorMissionProvider in App.jsx — the new innermost provider:
 *   CreatorMissionProvider
 *     └─ CreatorCoachProvider  ← here
 *        └─ BrowserRouter
 *           └─ CoachBridge (renderless, writes coachSession)
 */

import React, {
  createContext,
  useContext,
  useReducer,
  useCallback,
  useMemo,
} from 'react';

import { createBlankCoachSession } from '../models/coachModel';

// ── Action type constants ──────────────────────────────────────────────────────
const A = {
  SET_SESSION:     'SET_SESSION',
  SET_GENERATING:  'SET_GENERATING',
  COMPLETE_ACTION: 'COMPLETE_ACTION',
  REFRESH_TICK:    'REFRESH_TICK',
};

// ── Initial state ─────────────────────────────────────────────────────────────
const initialState = {
  coachSession:  createBlankCoachSession(),
  isGenerating:  false,
  refreshTick:   0,
};

// ── Reducer ───────────────────────────────────────────────────────────────────

/** Recompute completionProgress based on how many actions are done. */
function computeActionProgress(actions) {
  if (!actions?.length) return 0;
  const done = actions.filter(a => a.completed).length;
  return Math.round((done / actions.length) * 100);
}

function reducer(state, action) {
  switch (action.type) {

    case A.SET_SESSION:
      return { ...state, coachSession: action.payload, isGenerating: false };

    case A.SET_GENERATING:
      return { ...state, isGenerating: action.payload };

    case A.COMPLETE_ACTION: {
      const updatedPlan = state.coachSession.actionPlan.map(a =>
        a.id === action.payload ? { ...a, completed: true } : a,
      );
      return {
        ...state,
        coachSession: {
          ...state.coachSession,
          actionPlan: updatedPlan,
          // Store action completion progress on the session for UI use
          actionProgress: computeActionProgress(updatedPlan),
        },
      };
    }

    case A.REFRESH_TICK:
      return { ...state, refreshTick: state.refreshTick + 1 };

    default:
      return state;
  }
}

// ── Context ───────────────────────────────────────────────────────────────────
const CreatorCoachContext = createContext(null);

export function CreatorCoachProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);

  // ── Action creators ──────────────────────────────────────────────────────

  /** Write a newly-generated CreatorCoachSession. Called by CoachBridge. */
  const setCoachSession = useCallback(
    (session) => dispatch({ type: A.SET_SESSION, payload: session }),
    [],
  );

  /** Set the generating indicator. Called by CoachBridge. */
  const setGenerating = useCallback(
    (value) => dispatch({ type: A.SET_GENERATING, payload: value }),
    [],
  );

  /**
   * Mark a CoachAction as completed.
   * Called by the coach UI when the creator taps an action row.
   * @param {string} actionId
   */
  const completeAction = useCallback(
    (actionId) => dispatch({ type: A.COMPLETE_ACTION, payload: actionId }),
    [],
  );

  /**
   * Increment the refresh tick to force CoachBridge to regenerate even if
   * no upstream signal changed.
   */
  const refreshCoach = useCallback(
    () => dispatch({ type: A.REFRESH_TICK }),
    [],
  );

  // ── Context value ────────────────────────────────────────────────────────

  const value = useMemo(() => ({
    // Raw state
    state,

    // Convenience top-level accessors
    coachSession:  state.coachSession,
    isGenerating:  state.isGenerating,

    // Action creators
    setCoachSession,
    setGenerating,
    completeAction,
    refreshCoach,
  }), [state, setCoachSession, setGenerating, completeAction, refreshCoach]);

  return (
    <CreatorCoachContext.Provider value={value}>
      {children}
    </CreatorCoachContext.Provider>
  );
}

/**
 * Internal context hook — consumed by useCreatorCoach.js and CoachBridge.
 * Components should import useCreatorCoach from the public hook, not this.
 */
export function useCreatorCoachContext() {
  const ctx = useContext(CreatorCoachContext);
  if (!ctx) {
    throw new Error('useCreatorCoachContext must be used within CreatorCoachProvider');
  }
  return ctx;
}
