/**
 * assistant/context/CreatorAssistantContext.jsx — Creator Assistant Context
 *
 * Module 10.1 — Realis AI Creator Assistant
 *
 * Stores the latest CreatorBriefing generated by creatorAssistantService.
 * It is a derived-state store: AssistantBridge writes to it; UI reads from it.
 *
 * ── State ─────────────────────────────────────────────────────────────────────
 *   briefing       — latest CreatorBriefing (see assistantModel.js)
 *   isGenerating   — true while AssistantBridge is computing a new briefing
 *
 * ── Actions ───────────────────────────────────────────────────────────────────
 *   SET_BRIEFING   — replace briefing with a freshly-generated one
 *   SET_GENERATING — toggle the isGenerating loading flag
 *
 * ── Public API ────────────────────────────────────────────────────────────────
 *   briefing           — CreatorBriefing
 *   isGenerating       — boolean
 *   refreshBriefing()  — explicitly request AssistantBridge to regenerate
 *                        (increments a trigger counter the bridge watches)
 *   setBriefing(b)     — write a generated briefing (called by AssistantBridge)
 *   setGenerating(v)   — set the loading indicator (called by AssistantBridge)
 *
 * ── Mounting ──────────────────────────────────────────────────────────────────
 * Wrapped inside CreatorLearningProvider in App.jsx, making it the innermost
 * provider before BrowserRouter:
 *   CreatorLearningProvider
 *     └─ CreatorAssistantProvider  ← here
 *        └─ BrowserRouter
 *           └─ AssistantBridge (renderless, writes briefing)
 */

import React, {
  createContext,
  useContext,
  useReducer,
  useCallback,
  useMemo,
} from 'react';

import { createBlankBriefing } from '../models/assistantModel';

// ── Action type constants ──────────────────────────────────────────────────────
const A = {
  SET_BRIEFING:   'SET_BRIEFING',
  SET_GENERATING: 'SET_GENERATING',
  REFRESH_TICK:   'REFRESH_TICK',
};

// ── Initial state ─────────────────────────────────────────────────────────────
const initialState = {
  briefing:      createBlankBriefing(),
  isGenerating:  false,
  refreshTick:   0,   // incremented by refreshBriefing() to signal the bridge
};

// ── Reducer ───────────────────────────────────────────────────────────────────
function reducer(state, action) {
  switch (action.type) {

    case A.SET_BRIEFING:
      return {
        ...state,
        briefing:     action.payload,
        isGenerating: false,
      };

    case A.SET_GENERATING:
      return { ...state, isGenerating: action.payload };

    // Increment tick — AssistantBridge watches this and re-generates
    case A.REFRESH_TICK:
      return { ...state, refreshTick: state.refreshTick + 1 };

    default:
      return state;
  }
}

// ── Context ───────────────────────────────────────────────────────────────────
const CreatorAssistantContext = createContext(null);

export function CreatorAssistantProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);

  // ── Action creators ──────────────────────────────────────────────────────

  /** Write a newly-generated CreatorBriefing. Called by AssistantBridge. */
  const setBriefing = useCallback(
    (briefing) => dispatch({ type: A.SET_BRIEFING, payload: briefing }),
    [],
  );

  /** Set the generating indicator. Called by AssistantBridge. */
  const setGenerating = useCallback(
    (value) => dispatch({ type: A.SET_GENERATING, payload: value }),
    [],
  );

  /**
   * Public action — increment the refresh tick to force a new briefing
   * generation even if the session count hasn't changed.
   * Exposed to UI via useCreatorAssistant().
   */
  const refreshBriefing = useCallback(
    () => dispatch({ type: A.REFRESH_TICK }),
    [],
  );

  // ── Context value ────────────────────────────────────────────────────────

  const value = useMemo(() => ({
    // Raw state
    state,

    // Convenience top-level accessors
    briefing:     state.briefing,
    isGenerating: state.isGenerating,

    // Action creators
    setBriefing,
    setGenerating,
    refreshBriefing,
  }), [state, setBriefing, setGenerating, refreshBriefing]);

  return (
    <CreatorAssistantContext.Provider value={value}>
      {children}
    </CreatorAssistantContext.Provider>
  );
}

/**
 * Internal context hook — consumed by useCreatorAssistant.js and AssistantBridge.
 * Components should import useCreatorAssistant from the public hook, not this.
 */
export function useCreatorAssistantContext() {
  const ctx = useContext(CreatorAssistantContext);
  if (!ctx) {
    throw new Error(
      'useCreatorAssistantContext must be used within CreatorAssistantProvider',
    );
  }
  return ctx;
}
